### ISSUE TITLE
Cleanup integration test

### ISSUE THREAD

**Issue by Ghebrechristos** [cedardevs/psi#101]
If the messages/ playload logic changes the test fail, it seems by default the the topic or state don't get cleanup. 
Ac:  
- [x] Integrate circle-ci with slack for notification 
- [ ] Cleanup before test start or after test (Note: i seen this on registry integration test)

Child of #87

**Comment by Ghebrechristos** [comment]
-[] Integrate circle-ci with slack

**Comment by mcquinne** [comment]
The behavior of messages bleeding over from one test run to the next seems to be an uncommon edge case that only shows up when running locally (i.e. not on CircleCI). Since this isn't truly a problem we're going to close this for now.
