### ISSUE TITLE
Update s3-archiver and metadata-scraper

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/psi#102]
We now have an engine specifically for handling http requests to an external url. To use it, s3-archiver and metadata-scraper need to put a message in its queue rather than make the post themselves. 
AC: s3-archiver and metadata-scraper do not do http posts, but instead send the payload in a message to metadata-publisher.

Child of #87

**Comment by cEsterlein** [comment]
https://github.com/cedardevs/ingest-engines/tree/metadata-publisher

You can see s3-archiver and metadata-scraper send a message to the metadata-publisher engine instead of making a post. I updated the readme and configs. Pushed images, deployed to CU server.
