### ISSUE TITLE
lastUpdate -> ingestTime

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/psi#103]
Scripts that produce isoLite need to fill in a publish date. Currently metadata-scraper sets the 'lastUpdated' field with the current time and then metadata-publisher will pass it through or set it if it's undefined. 

We want to rename the variable from lastUpdated to ingestTime. This will require updating metadata-scraper, metadata-publisher, the dscovr script, and possibly some tests.

AC: lastUpdated is not a field in the payload from CI to PSI, ingestTime is, and the dscovr script uses it to set the publish date.

Child of #87

**Comment by cEsterlein** [comment]
It makes sense that there would be a lastUpdated field for each granule, but maybe registry should set that?
