### ISSUE TITLE
Metadata-publisher circuit breaker

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/psi#105]
AC: Metadata-publisher does not drop data, it maintains the order in which messages arrive, it does not get caught in a loop and repeatedly send requests to Inventory Manager. 

We need to employee [the circuit breaker pattern](https://martinfowler.com/bliki/CircuitBreaker.html)

We also need a way to notify someone when the circuit breaks.

**Comment by cEsterlein** [comment]
If (status >= 400  && status  < 500 ): you messed up, send an error to ingest manager .
if(status >= 500):  inventory manager is down, try again later

**Comment by cEsterlein** [comment]
example 404 
https://sciapps.colorado.edu/ingest-manager/granule/show/2829

**Comment by cEsterlein** [comment]
Cant get the darn thing to connect to PSI! 

Config looks good
https://github.com/cedardevs/cu-server-admin/blob/master/roles/deploy-stack/files/common_ingest/docker/secrets/metadata-publisher.yml

Proxy pass is in place

I keep getting a 404 even thought the URL looks right compared to the proxy pass. If the URL is correct, we get 404s when registry isnt up, not 500s like we should. 

Hopefully someone has better luck when they review this story.
