### ISSUE TITLE
Load metadata for OER Videos

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#114]
Simulate metadata publishing from MS/MD based on metadata records provided to us (See https://www.nodc.noaa.gov/search/granule/ and search for "EX1603". Download any or all metadata records found.)

**Comment by StrayCat1** [comment]
Sent some ISO XML to PSI 
https://sciapps.colorado.edu/psi/metadata/granule/4d989197-d4a9-4a2b-a579-5eb67b44c3d9

We realized the script wrapper tries to run again it because it tries to run against every message. 

We need to figure out how to split/filter messages in the script-wrapper.

**Comment by StrayCat1** [comment]
Also, I thought I remember them saying that these metadata records were isoLite. That does not appear to be the case.

**Comment by StrayCat1** [comment]
It works! 
https://sciapps.colorado.edu/psi/metadata/granule/4d989197-d4a9-4a2b-a579-5eb67b44c3d9
