### ISSUE TITLE
Re-evaluate containerized ingress

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#116]
Create a single nginx container to serve as the entrypoint for everything on sciapps.

- [ ] Include sciapps certificates
- [ ] Admin usernames/passwords
- [x] Routing for all exposed apps (onestop, kibana, rabbit console, etc.)

**Comment by mcquinne** [comment]
I think [Ambassador](https://www.getambassador.io/) looks really promising and I've got it working in the [helm charts](https://github.com/cedardevs/helm-charts) for our platform.

I haven't gotten certificates or passwords working, but I think we should do that as part of #151 when we deploy to the CU servers.

**Comment by Ghebrechristos** [comment]
I think Ambassador is a great choose!
