### ISSUE TITLE
Harvest 500 OER video records

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#134]
Write a script to download OER video metadata (re-purpose of move from OneStop?)

-  [ ] Post 500 OER video metadata records to PSI granule endpoint

**Comment by StrayCat1** [comment]
Can we settle on 500 for this test run? 

The collection and granules were assigned random UUIDs. Looks like most of them got parsed. I havent hooked up the connector to feed them into onestop yet. 

https://docs.google.com/document/d/1fh7KZp2a5xNmEvl-_V-hjCJ45NgmaNUOu41nAOD8KCc/edit?usp=sharing

**Comment by dneufeldcu** [comment]
500 it is!

**Comment by StrayCat1** [comment]
alright, there is an OER collection and 500 granules with parsed attributes in inventory manager, but  I need this to go into onestop before I am gonna consider it done.

**Comment by StrayCat1** [comment]
And yet another search result for EX1603 from a very similar looking NODC geoportal. 

https://www.nodc.noaa.gov/archivesearch/rest/find/document?searchText=EX1603

**Comment by StrayCat1** [comment]
The collection in IM: https://sciapps.colorado.edu/psi/metadata/collection/8b5565cb-270b-4bbd-bc8a-665e4680f75c
A granule the references it:
https://sciapps.colorado.edu/psi/metadata/granule/c6bca67c-f59b-4057-b265-f1c249f76e3c
Triggered the ETL, but not seeing the granule show up in the search index. 
debugging....

**Comment by StrayCat1** [comment]
Inserted link protocol into the iso xml
Example- 
sciapps.colorado.edu/psi/metadata/granule/ffe0820d-c7d1-49f1-9551-be8053601095

**Comment by mcquinne** [comment]
We now have [a tarball](https://drive.google.com/open?id=0B2Z50BpkjOv5RzY2aGNNSHotbVN6aVlwbDlURXczaURhTlQ4) with 1 collection record + 499 granules that have been modified to have the correct parentIds and linkProtocols and have been loaded into psi + onestop.
