### ISSUE TITLE
Evaluate FaaS Implementations

### ISSUE THREAD

**Issue by ajakz** [cedardevs/psi#142]
Goal:
Evaluate and decide on FaaS system to use on the Kubernetes cluster for both internal functions (like metadata parsing) and future SME scripts. 

Function-as-a-Service systems/frameworks
- Open Faas
- OpenWhisk
- Fission
- Kubeless
- Fn Project
- Serverless

AC:
- [x] FaaS decision made and agreed upon by team (potentially resolved by an agile learning type presentation)

Time Box:
3 Days

**Comment by mcquinne** [comment]
Note: we should evaluate how valuable it would truly be to use the serverless framework abstraction given that a) migrating platforms is probably low cost for now, and b) it seems to be a fairly leaky abstraction anyway...

**Comment by mcquinne** [comment]
We've selected OpenWhisk as our FaaS solution. It's an Apache project, it's supported by RedHat, it's used in OpenShift, etc. Seems like a solid choice.
