### ISSUE TITLE
Remove ScriptWrapper

### ISSUE THREAD

**Issue by ajakz** [cedardevs/psi#148]
Goal:
ScriptWrapper functionality is fully replaced by serverless functions.

AC:
- [x] Confirm all functionality of ScriptWrapper is covered elsewhere
- [x] Ensure Splitter works with new functions
- [x] Delete ScriptWrapper

**Comment by Ghebrechristos** [comment]
Decide to create a new folder for serverless related work and moved dscovr openwhisk implementation to it
