### ISSUE TITLE
Deploy gluster + heketi in k8s

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/psi#150]
We need a shared volume for the common ingest  components to use and it turns out that the default storage class in cloud providers does not support the ReadWriteMany mode that we need.

So, let's deploy gluster using k8s and create a separate storage class to use when shared volumes are needed.

Required by #111

**Comment by StrayCat1** [comment]
I was able to deploy a gluster cluster to a GKE k8s cluster and use it to mount a shared volume to all the ingest-engines. 

To do that, I found a repo that got me 90% there and then I made some tweaks to make it work. Here is the fork on
https://github.com/StrayCat1/gke-glusterfs-heketi

Next steps- 
- [ ] see if kubespray has a solution for installing gluster 
- [ ] write ansible scripts to automate the steps necessary to install gluster on k8s nodes (non-GKE)
