### ISSUE TITLE
Replace CU Deployment w/ k8s

### ISSUE THREAD

**Issue by forgo** [cedardevs/psi#151]
Building on the results of #111, we would like to:

- [ ] Install Kubernetes on all CU VMs in lieu of docker swarm
- [ ] Create a StorageClass for gluster storage
- [ ] Update deployment tools to deploy to k8s via helm
- [ ] Deploy all our software on the k8s clusters
- [ ] Set up the main ingress with our sciapps certificate
- [ ] Add basic auth for protected services

**Comment by mcquinne** [comment]
Recreated as cedardevs/cu-server-admin#20
