### ISSUE TITLE
Determine where analysis logic lives

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/psi#157]
As a PSI engineer, I want to determine the best place for the validation logic to execute. i.e. is it folded into the registry? Is it part of a separate processing application?

Things to consider:
- This logic should run against ALL metadata that comes through the system.
- It will (initially) be implemented in a kafka streams app
- We need to balance separation of concerns into microservices vs minimizing our deployment footprint to help federal IT

AC:
We know where to implement the validation workflow.

**Comment by StrayCat1** [comment]
We want to implement the validation work after the parsing step. This rules out registry. 
I guess an important thing to consider is who is this validation for? Are these validation rules for OneStop or everything downstream of IM? 

I think it makes sense to do what Arianna and Evan diagrammed - parse, analyze, validate in a single app before putting it on the topic that OneStop is connected to.

**Comment by Ghebrechristos** [comment]
The analysis logic will live in the stream-manager app
