### ISSUE TITLE
Evaluate and select streaming technology

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#16]
Use case - We need a streaming technology cause...

- [x] Kafka Streaming
- [ ] Onyx
- [ ] Storm
- [ ] Spark

**Comment by mcquinne** [comment]
In the process of writing the Google doc "MDMS Use Case: DSCOVR" for #22 I believe we've also resolved this issue by suggesting a specific approach built around Apache Kafka.

**Comment by ChrisEsterlein** [comment]
Kafka + Kafka streams
