### ISSUE TITLE
Refactor metadata-recorder-processor using lightengine approach

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#18]
Goals:
1. Refactor metadata-recorder to use the light-engine base
2. Reconsider how metadata is recorded:
    a. i.e. should we publish metadata to rabbit so that other engines/psi can read it?
    b. Do we need to continue publishing via HTTP POST?
    c. Reassess what attributes get published
    d. Should we be doing datastream-specific recording in the ingest system?

Considerations:
1. How does the metadata-recorder on github relate to the one in stash? Do we need to move logic from stash out to metadata-recorder?
1. Maybe make a new engine instead of updating metadata-recorder?

**Comment by Ghebrechristos** [comment]
1. we decide to create a new engine (metadata-scraper) using light engine 
2. For now the engine is publishing via HTTP POST
3. Attributes that get published: 
                dataStream
                trackingId
                checkSum  
                fileName 
                filePath  
                fileSize  
4. dataset specific scraping will be done via PSI
