### ISSUE TITLE
Associate Dscovr granule to collection level metadata

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#20]
Use the metadata record found here:
https://www.ngdc.noaa.gov/metadata/published/NOAA/NESDIS/NGDC/STP/Space_Weather/iso/

And flatten the collection metadata into the granule blob.

Question: How we will retrieve the flattened granule metadata? Do we need to? Store raw metadata?

**Comment by mcquinne** [comment]
The granule ISOLite records produce by the SME script are correctly generating parentIdentifiers which match these collections... so it's done!
