### ISSUE TITLE
Write up of features/requirements for Dscovr

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#22]
Using the dscovr datastream stories at left capture features and explore how it would be done using existing technology; compare and contrast with one or more of technologies identified. e.g. kafka or onyx and cassandra.

**Comment by mcquinne** [comment]
The Google doc entitled "MDMS Use Case: DSCOVR" lays out the requirements to implement DSCOVR in detail and provides a proposed approach to do so.

**Comment by zebdelk** [comment]
Review of document: Made a few minor copy edits and suggestions for clarity. Looks very thorough!

**Comment by ChrisEsterlein** [comment]
The only concern I have about this is that we aren't doing anything to populate the dscovr catalog like the old processor was doing. 

Closing this story. If the above concern is valid, it will re-emerge.
