### ISSUE TITLE
Design API to publish metadata

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#33]
- [ ] Define and document initial endpoints for HTTP webapp
- [ ] How we are organizing kafka topics
- [ ] Language discussion (Meeting scheduled and discussed)

**Comment by dneufeldcu** [comment]
/psi/api/granule  { dataStream: "DSCOVR". trackingId: "abc-def-g"}

**Comment by ChrisEsterlein** [comment]
First pass is done 
one endpoint- /metadata/granule
