### ISSUE TITLE
Update metadata scaper

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#34]
- [x] Dscovr datastream posts to api-psi

**Comment by Ghebrechristos** [comment]
The client base url is configurable on the metadta-scraper engine

**Comment by cEsterlein** [comment]
@Ghebrechristos  This story might be a bit more involved than assumed. Metadata-scraper is part of the common-ingest stack, the psi-api is part of the psi stack. We need to allow metadata-scraper to send an http request to psi-api. We can do this by allowing inter-stack communication among services (if that's a thing), or proxy psi-api w/ nginx (done) and then configure metadata-scraper to use the public endpoint (not done). The later seems to come with security implications.

**Comment by cEsterlein** [comment]
#52
