### ISSUE TITLE
First pass on indexing

### ISSUE THREAD

**Issue by cEsterlein** [cedardevs/psi#53]
Listen to parsed granules topic, transform as necessary, post to onestop elastic search.

**Comment by mcquinne** [comment]
We want to try using Kafka Connect to do this to see what it can provide us and get do some general learning about it.

**Comment by mcquinne** [comment]
I think this is good for now, it simple takes json from `parsed-granules` and puts it in an index. We can revisit when we want to use a schema for the messages on the topic and/or customize the mapping of the elasticsearch index.
