### ISSUE TITLE
Use MetadataParser on ISOLite output

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/psi#58]
After we get the ISOLite script in #55, we should apply the MetadataParser code from OneStop to parse the XML into the shape that will be indexed in Elasticsearch.

**Comment by cEsterlein** [comment]
https://github.com/cedardevs/psi/commit/fa898bccfaf3f617f31b189fe16e362e13683e47
and
https://github.com/cedardevs/psi/commit/ca266dbf0b58217e276b81f86c02bf0cc76e4d1f

The first commit shows we added metadata parser as a script and the second shows that we created a service that reads from a topic with IsoLite and outputs to the parsed-granules topic.
