### ISSUE TITLE
Bug : CI event order

### ISSUE THREAD

**Issue by cEsterlein** [cedardevs/psi#67]
child of #87
We are creating events out of order. This can prevent re-triggering if one event failed, but then another changes it. 

Like in this example- https://sciapps.colorado.edu/ingest-manager/granule/show/660

AC: Time-box 2 days are report out any insights on this story; re-evaluate

**Comment by mcquinne** [comment]
Step one: ask Asheville if they've seen it before.

**Comment by Ghebrechristos** [comment]
The event order behavior only appears on Cu-server 
Note: 
Currently it may not be a big issue but it can cause a problem down in the road (specifically when a stream need to be restarted through the the manager ui).

**Comment by Ghebrechristos** [comment]
let it reemerge (maybe after we set up kubernetes )

**Comment by cEsterlein** [comment]
Closing it, and letting it re-emerge.
