### ISSUE TITLE
resetting consumers

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/psi#73]
We will need our stream apps capable of replaying events. 

[This article](https://www.confluent.io/blog/data-reprocessing-with-kafka-streams-resetting-a-streams-application/) shows how to enable reset in your application and then trigger it from the kafka CLI, but we probably don't want to use the CLI to do it.

How do we want to trigger a restart?

Child of #87

**Comment by mcquinne** [comment]
Is there a way to do a global restart without using the CLI tool?

**Comment by Ghebrechristos** [comment]
we have a playbook for resetting under [cu-server-admin](https://github.com/cedardevs/cu-server-admin/blob/master/resetApplication.yml) repo. it will prompt the user for inputs: service name that need to be scale down, application/group id and input topic of the service that need to be reset
