### ISSUE TITLE
Evaluate existing validation logic

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#79]
As a PSI developer, I want to understand the existing validation code to determine how it should be implemented as a workflow.

Jason S. has a JAR that runs validation and we want to run it in InvMgr

This is code is stored in the partner organizational code repo.  See https://git.xx.xx.gov/metadata/MetadataSubmission

**Comment by dneufeldcu** [comment]
AC: What are the business rules for validation? Document here.

**Comment by StrayCat1** [comment]
AccessProtocolCheck-
- HTTP-  URI starts with "HTTP://"
- HTTPS  - starts with "HTTPS://"
- FTP - starts with "FTP://"
- OPeNDAP - true
- UNIDATA:THREDDS - true
- NOAA:LAS - true
- download - true if response content type is not html/text
- OGC:WMS - true
- OGC:WCS - true

**Comment by StrayCat1** [comment]
AccessUrlCheck
- find all links
- assert 200 response

**Comment by StrayCat1** [comment]
DateFormatCheck
- find all dates
- make sure the date at xpath is one of the valid formats

```java
//Here are the various formats-
DateTimeFormatter yyMmDdFormat = createDateFormat("yyyy-MM-dd");
DateTimeFormatter yyMmFormat = createDateFormat("yyyy-MM");
DateTimeFormatter yyFormat = createDateFormat("yyyy");
DateTimeFormatter ssFormat = createDateFormat("yyyy-MM-dd'T'HH:mm:ss");
DateTimeFormatter ssLiteralZFormat = createDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
DateTimeFormatter ssZFormat = createDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
DateTimeFormatter ssSsssFormat = createDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSS");

//Here are the list of acceptable variations-
List<DateTimeFormatter> dateList = asList(yyMmDdFormat, yyMmFormat, yyFormat);
List<DateTimeFormatter> dateTimeList = asList(ssFormat, ssLiteralZFormat, ssZFormat, ssSsssFormat);
List<DateTimeFormatter> gmlList = asList(yyFormat, yyMmFormat, yyMmDdFormat, ssFormat, ssLiteralZFormat, ssZFormat, ssSsssFormat);

//Here are the xpaths next to their list of acceptable variations
DATE_TO_FORMAT_MAP.put("//gml:beginPosition", gmlList);
DATE_TO_FORMAT_MAP.put("//gml:endPosition", gmlList);
DATE_TO_FORMAT_MAP.put("//gml:timePosition", gmlList);
DATE_TO_FORMAT_MAP.put("//gco:Date", dateList);
DATE_TO_FORMAT_MAP.put("//gco:DateTime", dateTimeList);
```

**Comment by StrayCat1** [comment]
FileIdentifierCheck-
- Must have a fileIdentifier or DOI

```
private final String FILE_ID_XPATH = "/gmi:MI_Metadata/gmd:fileIdentifier";
private final String DOI_XPATH = "//gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:identifier/gmd:MD_Identifier/gmd:code[contains(., 'DOI') or contains(.,'doi') or contains(.,'Doi')]";
```

**Comment by StrayCat1** [comment]
ParentIdentifierCheck-
- does it have a parent id? if not, return true. If yes, continue
- does it have more than one? fail
- have we seen it before (on this round of submissions)? if yes, pass. else, fail. (requires state)

**Comment by StrayCat1** [comment]
GranuleHasParentIdentifierCheck-
- if it is a granule and does not have a parent id, fail
- if it is a granule and has multiple parent ids, fail

(Really this is almost the same as the parent identifier check.)

**Comment by StrayCat1** [comment]
TitleCheck-
- do we have a title at this path- "//gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title"

**Comment by StrayCat1** [comment]
All of the aforementioned checks can be found in there classes  -
https://git.ncdc.noaa.gov/metadata/MetadataSubmission/tree/master/src/main/java/gov/noaa/ncei/validation/validityChecks
