### ISSUE TITLE
Bug: dscovr f1m collection not parsing

### ISSUE THREAD

**Issue by cEsterlein** [cedardevs/psi#81]
dscovr's faraday 1 minute averages collection metadata record is not making it past the metadata parser, meaning neither the collection nor the granules associated with that collection make it to onestop.

Child of #87

**Comment by mcquinne** [comment]
Here's a link to the failing metadata record: https://www.ngdc.noaa.gov/metadata/published/NOAA/NESDIS/NGDC/STP/Space_Weather/iso/xml/dscovr_f1m.xml

**Comment by Ghebrechristos** [comment]
this record consists a none well-formed character on line number 3314

**Comment by cEsterlein** [comment]
@Ghebrechristos Should we wait for him to fix it and then see if it works? Otherwise, this seems closed.

**Comment by Ghebrechristos** [comment]
@cEsterlein He can do what he wants to do, at least for now we don't really care about this but in the future we can use the metadata folks validation scripts to take care of it
