### ISSUE TITLE
Identity function in script wrapper

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#83]
Identify function: `x => x`

Goal:
- Don't call the iso parsing logic as an external script since it is already in the script-wrapper code

e.g.:

```yml
stream:
    command: noop
```

Child of #87

**Comment by Ghebrechristos** [comment]
It pass through ( returns the current msg with out doing anything ) when the command value is "echo" 
 stream:
    command: echo

**Comment by cEsterlein** [comment]
Alright so scriptCaller checks to see if command is 'echo' and if it is, then it returns the message. Simple solution, calling this done.
