### ISSUE TITLE
Revisit changelog topics

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#84]
The registry streams app creates several internal changelog topics, some of which have the same information as other topics we are declaring, e.g. `parsed-granules` and `metadata-aggregator-parsed-granules-changelog`

Goal:
- Do not store all parsed messages forever twice

So either:
1. Use `parsed-granules` and `parsed-collections` as the changelogs and prevent the creation of the additional topics
1. Let `parsed-granules` and `parsed-collections` behave like default topics (limited retention) and let the streams app make its changelogs

Child of #87

**Comment by Ghebrechristos** [comment]
Set parsed granule and collection topics to a default clean up config values and enabled the creation of the change logs with an empty config for now.

**Comment by mcquinne** [comment]
Child of #87

**Comment by cEsterlein** [comment]
https://github.com/cedardevs/psi/commit/5e22f72b78ec583a3e92120c30a35d22e7f80398

So if I understand this correctly, parsed-granules and parsed-collections are not ephemeral and the KTable changelogs are now this canonical source of truth for collection and granule information. 

I need to double check the names of those topics,  but they should be - 
'metadata-aggregator-parsed-granules-changelog'
and
'metadata-aggregator-parsed-collections-changelog'

**Comment by mcquinne** [comment]
LGTM 👍
