### ISSUE TITLE
kafka manager image?

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#85]
- [x] Check for existing image
- [x] Add Dockerfile to repo

**Comment by cEsterlein** [comment]
there are non-official images for kafka-manager, such as this one: https://hub.docker.com/r/sheepkiller/kafka-manager/
Which might not be a bad way to go. It looks like we can pass the configuration settings. The one we care about is 'play.http.context' in this file:
https://github.com/cedardevs/psi/blob/master/kafka-manager/kafka-manager-1.3.3.16/conf/application.conf
That application context must match the nginx proxy or your web client will fail to access css and other resources. 
Anyway, for now I just added the kafka-manager project with the (sbt) built binaryand configs that we need to build the image and run the program.  At least other people can build the image we have on dockerhub but it might be worth looking in to someone else's image if we get sick of managing our own. 
https://github.com/cedardevs/psi/tree/master/kafka-manager
