### ISSUE TITLE
First pass: SME Error handling

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#89]
- [ ] Collection record doesn't parse (see #81)
- [ ] SME script fails

Child of #87

**Comment by mcquinne** [comment]
The goal for now:
- Capture script execution info
- Put it on a topic
- Optionally: send it to elasticsearch

**Comment by Ghebrechristos** [comment]
its on a branch handle-sme-error:
i am using kstream branch  to route records based on the incoming messages, in the case of a good message, it works as i want it but in the case of bad message its breaking my stream out.
