### ISSUE TITLE
Dockerize CI

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#9]
- [x] CCI can be run in development via docker

**Comment by rongxanh88** [comment]
Ashville components can be run in development via docker. Boulder components still need to be dockerized.

**Comment by rongxanh88** [comment]
I have integrated metadata-recorder-processor. Just need to add either the old dscovr-processor, or the new one being built by Semere and we can start testing a stream.

**Comment by Ghebrechristos** [comment]
Engines that we need for DSCOVR use cases are dockerize
