### ISSUE TITLE
Create a metadata-publisher engine

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/psi#91]
Child of #87
Currently engines like `s3-archiver` and `metadata-scraper` send HTTP POSTs directly to the PSI API. This introduces the risk that ingest streams could fail if the API is unavailable.

Instead, those engines should publish an additional rabbit message to a new engine which is responsible for publishing it to PSI. That way if PSI is down ingest streams can proceed but we still have a record of the metadata that still needs to be published.

AC:
- A new CI engine exists which accepts maps of metadata and publishes them to the PSI API.

**Comment by cEsterlein** [comment]
Here is the branch: https://github.com/cedardevs/ingest-engines/tree/metadata-publisher
