### ISSUE TITLE
bug: script-wrapper config env var

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/psi#96]
Script wrapper will scan the environment for vars starting with psi_. One of those vars, psi_config_location, can be used to configure the location of an external yml config file. However, that is currently broken. When it picks up PSI_CONFIG_LOCATION, it needs to prepend 'file://' to the value or we get the exception we see now about an MalformedUrl.

**Comment by mcquinne** [comment]
Will be resolved by #152
